// Copyright 2026 Rwx-G (Lorica)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Pure `instant-acme` protocol driver.
//!
//! Each entry point drives an ACME order end to end - account creation,
//! order, authorizations, challenge readiness, CSR finalization, and
//! certificate polling - and returns the issued PEM bundle. None of these
//! functions touch a configuration store, an audit log, or any
//! management-plane state; the caller persists the returned
//! [`IssuedCertificate`] however it sees fit.

use instant_acme::{
    Account, AccountCredentials, AuthorizationStatus, ChallengeType, Identifier, NewAccount,
    NewOrder, OrderStatus, RetryPolicy,
};
use tracing::info;

use crate::config::AcmeConfig;
use crate::dns_challengers::DnsChallenger;
use crate::error::AcmeError;

/// An issued certificate bundle: the PEM-encoded chain plus the PEM-encoded
/// private key generated for the CSR.
#[derive(Debug, Clone)]
pub struct IssuedCertificate {
    /// PEM-encoded certificate chain returned by the ACME CA.
    pub cert_pem: String,
    /// PEM-encoded private key matching the issued certificate.
    pub key_pem: String,
}

/// Strategy for publishing and retracting HTTP-01 challenge tokens.
///
/// The driver calls [`present`](Http01ChallengeSolver::present) for every
/// challenge before signalling readiness, and
/// [`cleanup`](Http01ChallengeSolver::cleanup) for every token once the
/// order resolves (success or failure). The implementation is responsible
/// for making `token -> key_authorization` reachable at
/// `/.well-known/acme-challenge/{token}`.
#[async_trait::async_trait]
pub trait Http01ChallengeSolver: Send + Sync {
    /// Publish `key_authorization` so it is served for `token`.
    ///
    /// Fallible since Story 9.1 AC #9 (breaking change, budgeted
    /// there): a partial distribution - the fleet case in Story 9.5,
    /// or a local persist failure that would 404 the challenge on a
    /// worker - must abort the order BEFORE `set_ready()` tells the
    /// CA to validate, instead of racing an opaque validation failure.
    async fn present(&self, token: String, key_authorization: String) -> Result<(), AcmeError>;
    /// Retract a previously-published `token`.
    async fn cleanup(&self, token: &str);
}

/// Strip the `*.` prefix from a wildcard domain to get the base domain
/// for the `_acme-challenge` TXT record.
pub fn acme_dns_base_domain(domain: &str) -> &str {
    domain.strip_prefix("*.").unwrap_or(domain)
}

/// Generate a CSR and matching key pair covering every domain in `domains`.
/// Returns the DER-encoded CSR bytes and the PEM-encoded private key.
///
/// `finalize_csr` is the explicit-CSR variant in instant-acme 0.8; the
/// sibling `finalize()` would use a fresh rcgen key generated by the crate
/// (requires the `rcgen` feature, which we do not enable).
fn generate_csr(domains: &[String]) -> Result<(Vec<u8>, String), AcmeError> {
    let mut params =
        rcgen::CertificateParams::new(domains.to_vec()).map_err(|e| AcmeError::Csr(e.to_string()))?;
    params.distinguished_name = rcgen::DistinguishedName::new();
    let private_key = rcgen::KeyPair::generate().map_err(|e| AcmeError::Csr(e.to_string()))?;
    let csr = params
        .serialize_request(&private_key)
        .map_err(|e| AcmeError::Csr(e.to_string()))?;
    Ok((csr.der().to_vec(), private_key.serialize_pem()))
}

/// Build (or load) an ACME account against the directory in `config`.
async fn build_account(config: &AcmeConfig) -> Result<Account, AcmeError> {
    let contact = config.contact_email.as_ref().map(|e| format!("mailto:{e}"));
    let contact_refs: Vec<&str> = contact.iter().map(|s| s.as_str()).collect();

    // instant-acme 0.8 (audit L-15) : `Account::create` moved to a
    // builder-mediated path. The builder owns the HTTP client (default
    // `hyper-rustls` feature) ; `directory_url` is now an owned `String`.
    let (account, _) = Account::builder()
        .map_err(|e| AcmeError::Account(e.to_string()))?
        .create(
            &NewAccount {
                contact: &contact_refs,
                terms_of_service_agreed: true,
                only_return_existing: false,
            },
            config.directory_url().to_string(),
            None,
        )
        .await
        .map_err(|e| AcmeError::Account(e.to_string()))?;
    Ok(account)
}

/// Drive an ACME order to issuance using the HTTP-01 challenge.
///
/// Supports multi-domain SAN certificates (one order, N challenges). The
/// `solver` publishes each challenge token where the proxy data plane can
/// serve it; tokens are retracted regardless of the order outcome.
pub async fn issue_http01(
    config: &AcmeConfig,
    domains: &[String],
    solver: &dyn Http01ChallengeSolver,
) -> Result<IssuedCertificate, AcmeError> {
    let account = build_account(config).await?;

    // Create order with all domains as identifiers.
    let identifiers: Vec<Identifier> = domains.iter().map(|d| Identifier::Dns(d.clone())).collect();
    let mut order = account
        .new_order(&NewOrder::new(&identifiers))
        .await
        .map_err(|e| AcmeError::Order(e.to_string()))?;

    // instant-acme 0.8 (audit L-15) : authorizations is now a stream-style
    // iterator yielding `AuthorizationHandle`s ; we iterate once, store each
    // token + signal readiness on the same handle, then poll the order for
    // "all auths valid" via the new `poll_ready` helper. Cleanup of stored
    // tokens happens in both the success and failure paths so the proxy
    // never serves a stale challenge after the order resolves.
    let mut authorizations = order.authorizations();
    let mut stored_tokens: Vec<String> = Vec::new();
    // Collected instead of `?`-returned so the failure path below can
    // retract every token already presented. Story 9.1 AC #9: a
    // failed `present` aborts here, BEFORE `set_ready()` tells the CA
    // to validate (previously `present` was infallible and readiness
    // fired on the next line even when some serving node had no
    // token). The same restructure closes a pre-existing leak where
    // an in-loop `?` on a challenge error returned without cleaning
    // up already-presented tokens.
    let setup_result: Result<(), AcmeError> = 'setup: {
        while let Some(result) = authorizations.next().await {
            let mut authz = match result {
                Ok(a) => a,
                Err(e) => break 'setup Err(AcmeError::Order(e.to_string())),
            };
            if matches!(authz.status, AuthorizationStatus::Valid) {
                continue;
            }
            let mut challenge = match authz.challenge(ChallengeType::Http01) {
                Some(c) => c,
                None => break 'setup Err(AcmeError::NoChallenge("HTTP-01")),
            };
            let key_authorization = challenge.key_authorization();
            let token = challenge.token.clone();
            if let Err(e) = solver
                .present(token.clone(), key_authorization.as_str().to_string())
                .await
            {
                break 'setup Err(e);
            }
            stored_tokens.push(token);
            if let Err(e) = challenge.set_ready().await {
                break 'setup Err(AcmeError::Order(e.to_string()));
            }
        }
        Ok(())
    };
    // `authorizations` borrows `order` ; let NLL release the borrow here so
    // the next `order.poll_ready()` call can re-borrow mut.
    let _ = authorizations;

    if let Err(e) = setup_result {
        // Retract everything already published so no node keeps
        // serving a challenge for an order that will never validate.
        for token in &stored_tokens {
            solver.cleanup(token).await;
        }
        return Err(e);
    }

    // Wait for all authorizations to become valid (or hit a terminal
    // failure). `poll_ready` exponentially backs off and returns the final
    // OrderStatus.
    let ready_status = order
        .poll_ready(&RetryPolicy::default())
        .await
        .map_err(|e| AcmeError::Order(e.to_string()));

    // Clean up all challenge tokens regardless of outcome - the proxy must
    // not serve a stale token after the order resolves either way.
    for token in &stored_tokens {
        solver.cleanup(token).await;
    }

    let ready_status = ready_status?;
    if ready_status != OrderStatus::Ready {
        return Err(AcmeError::NotReady(format!("{ready_status:?}")));
    }

    finalize_and_poll(&mut order, domains).await
}

/// Drive an ACME order to issuance using the automated DNS-01 challenge.
///
/// Supports multi-domain and wildcard certificates. The `challenger`
/// creates the `_acme-challenge.<host>` TXT records and deletes them once
/// the order resolves (success or failure).
pub async fn issue_dns01(
    config: &AcmeConfig,
    domains: &[String],
    challenger: &dyn DnsChallenger,
) -> Result<IssuedCertificate, AcmeError> {
    let account = build_account(config).await?;

    // Create order with all domains as identifiers.
    let identifiers: Vec<Identifier> = domains.iter().map(|d| Identifier::Dns(d.clone())).collect();
    let mut order = account
        .new_order(&NewOrder::new(&identifiers))
        .await
        .map_err(|e| AcmeError::Order(e.to_string()))?;

    // instant-acme 0.8 (audit L-15) : authorizations is a stream-style
    // iterator and ChallengeHandle borrows the order, so we cannot keep all
    // challenge handles alive across two phases. Strategy : (1) walk the
    // iterator once to collect challenge metadata AND create the TXT records
    // ; (2) sleep for DNS propagation ; (3) walk the iterator a SECOND time
    // to call set_ready on each challenge ; (4) poll_ready for global
    // readiness. Cleanup of TXT records always runs in both happy and error
    // paths so the DNS provider does not accumulate stale
    // `_acme-challenge.<host>` rows.
    let mut created_records: Vec<String> = Vec::new(); // base_domains we created TXT for

    // Phase 1 : create TXT records.
    {
        let mut authorizations = order.authorizations();
        while let Some(result) = authorizations.next().await {
            let mut authz = result.map_err(|e| AcmeError::Order(e.to_string()))?;
            if matches!(authz.status, AuthorizationStatus::Valid) {
                continue;
            }
            let challenge = authz
                .challenge(ChallengeType::Dns01)
                .ok_or(AcmeError::NoChallenge("DNS-01"))?;
            let key_authorization = challenge.key_authorization();

            // For DNS-01, the TXT record value is the base64url-encoded
            // SHA-256 digest of the key authorization.
            use base64::Engine;
            use ring::digest;
            let digest_val = digest::digest(&digest::SHA256, key_authorization.as_str().as_bytes());
            let txt_value =
                base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(digest_val.as_ref());

            // For wildcards, strip the `*.` prefix for the TXT record domain.
            // `challenge.identifier()` gives an `AuthorizedIdentifier` whose
            // Display is the hostname.
            let auth_domain = challenge.identifier().to_string();
            let base_domain = acme_dns_base_domain(&auth_domain).to_string();

            challenger
                .create_txt_record(&base_domain, &txt_value)
                .await
                .map_err(AcmeError::DnsChallenge)?;

            created_records.push(base_domain);
        }
    }

    // Wait for DNS propagation.
    info!(domains = ?domains, "waiting for DNS propagation (30s)");
    tokio::time::sleep(std::time::Duration::from_secs(30)).await;

    // Phase 2 : signal readiness for all challenges by walking the
    // authorizations again. The second walk re-fetches server state so
    // set_ready transitions the now-pending challenge into PROCESSING.
    {
        let mut authorizations = order.authorizations();
        while let Some(result) = authorizations.next().await {
            let mut authz = result.map_err(|e| AcmeError::Order(e.to_string()))?;
            if matches!(authz.status, AuthorizationStatus::Valid) {
                continue;
            }
            let mut challenge = authz
                .challenge(ChallengeType::Dns01)
                .ok_or(AcmeError::NoChallenge("DNS-01"))?;
            challenge
                .set_ready()
                .await
                .map_err(|e| AcmeError::Order(e.to_string()))?;
        }
    }

    // Phase 3 : wait for all authorizations to become valid (or hit a
    // terminal failure). `poll_ready` exponentially backs off and returns
    // the final OrderStatus.
    let ready_status = order
        .poll_ready(&RetryPolicy::default())
        .await
        .map_err(|e| AcmeError::Order(e.to_string()));

    // Cleanup TXT records regardless of poll outcome.
    for base_domain in &created_records {
        let _ = challenger.delete_txt_record(base_domain).await;
    }

    let ready_status = ready_status?;
    if ready_status != OrderStatus::Ready {
        return Err(AcmeError::NotReady(format!("{ready_status:?}")));
    }

    finalize_and_poll(&mut order, domains).await
}

/// A single DNS-01 challenge the operator must satisfy in the manual flow.
#[derive(Debug, Clone)]
pub struct ManualDns01Challenge {
    /// The authorized identifier (hostname, including any `*.` wildcard).
    pub domain: String,
    /// The TXT record name to create (e.g. `_acme-challenge.example.com`).
    pub record_name: String,
    /// The TXT record value to set.
    pub txt_value: String,
    /// The ACME challenge URL, used to signal readiness in the confirm step.
    pub challenge_url: String,
}

/// The state produced by [`begin_manual_dns01`], carried between the two
/// steps of the manual DNS-01 flow.
#[derive(Debug, Clone)]
pub struct ManualDns01Order {
    /// The order URL, used to restore the order in the confirm step.
    pub order_url: String,
    /// Serialized account credentials (JSON) to restore the ACME account.
    pub account_credentials_json: String,
    /// The challenges the operator must satisfy (one per non-valid authz).
    pub challenges: Vec<ManualDns01Challenge>,
}

/// Step 1 of the manual DNS-01 flow: create an ACME order and extract the
/// DNS-01 challenge metadata WITHOUT creating any TXT record.
///
/// The returned [`ManualDns01Order`] carries the record names and values the
/// operator must publish, plus the order URL and serialized account
/// credentials the caller stores until [`finalize_manual_dns01`] is invoked.
pub async fn begin_manual_dns01(
    config: &AcmeConfig,
    domains: &[String],
) -> Result<ManualDns01Order, AcmeError> {
    // Create ACME account.
    let contact = config.contact_email.as_ref().map(|e| format!("mailto:{e}"));
    let contact_refs: Vec<&str> = contact.iter().map(|s| s.as_str()).collect();

    let (account, credentials) = Account::builder()
        .map_err(|e| AcmeError::Account(e.to_string()))?
        .create(
            &NewAccount {
                contact: &contact_refs,
                terms_of_service_agreed: true,
                only_return_existing: false,
            },
            config.directory_url().to_string(),
            None,
        )
        .await
        .map_err(|e| AcmeError::Account(e.to_string()))?;

    // Create order with all domains as identifiers.
    let identifiers: Vec<Identifier> = domains.iter().map(|d| Identifier::Dns(d.clone())).collect();
    let mut order = account
        .new_order(&NewOrder::new(&identifiers))
        .await
        .map_err(|e| AcmeError::Order(e.to_string()))?;

    // instant-acme 0.8 (audit L-15) : authorizations is now a stream-style
    // iterator of `AuthorizationHandle`. We extract the challenge metadata
    // synchronously here ; the confirm phase rebuilds the order from
    // credentials and re-walks the iterator to call `set_ready` by URL.
    let mut challenges: Vec<ManualDns01Challenge> = Vec::new();

    let mut authorizations = order.authorizations();
    while let Some(result) = authorizations.next().await {
        let mut authz = result.map_err(|e| AcmeError::Order(e.to_string()))?;
        if matches!(authz.status, AuthorizationStatus::Valid) {
            continue;
        }

        let challenge = authz
            .challenge(ChallengeType::Dns01)
            .ok_or(AcmeError::NoChallenge("DNS-01"))?;

        let key_authorization = challenge.key_authorization();
        let txt_value = key_authorization.dns_value();

        let auth_domain = challenge.identifier().to_string();
        let base_domain = acme_dns_base_domain(&auth_domain);
        let record_name = format!("_acme-challenge.{base_domain}");

        challenges.push(ManualDns01Challenge {
            domain: auth_domain,
            record_name,
            txt_value,
            challenge_url: challenge.url.clone(),
        });
    }
    // `authorizations` borrows `order` ; let NLL release the borrow here so
    // subsequent `order` calls can re-borrow mut.
    let _ = authorizations;

    // Serialize account credentials for later restoration.
    let account_credentials_json =
        serde_json::to_string(&credentials).map_err(|e| AcmeError::Credentials(e.to_string()))?;

    Ok(ManualDns01Order {
        order_url: order.url().to_string(),
        account_credentials_json,
        challenges,
    })
}

/// Step 2 of the manual DNS-01 flow: restore the order, signal readiness for
/// the challenges the operator published, and drive the order to issuance.
///
/// `challenge_urls` is the set of challenge URLs from
/// [`ManualDns01Order::challenges`] the caller wants to mark ready.
pub async fn finalize_manual_dns01(
    account_credentials_json: &str,
    order_url: &str,
    challenge_urls: &[String],
    domains: &[String],
) -> Result<IssuedCertificate, AcmeError> {
    // Restore ACME account from saved credentials.
    let credentials: AccountCredentials = serde_json::from_str(account_credentials_json)
        .map_err(|e| AcmeError::Credentials(e.to_string()))?;

    // instant-acme 0.8 (audit L-15) : `Account::from_credentials` moved onto
    // `AccountBuilder`. Restore an account from previously-stored credentials.
    let account = Account::builder()
        .map_err(|e| AcmeError::Account(e.to_string()))?
        .from_credentials(credentials)
        .await
        .map_err(|e| AcmeError::Account(e.to_string()))?;

    // Restore the order.
    let mut order = account
        .order(order_url.to_string())
        .await
        .map_err(|e| AcmeError::Order(e.to_string()))?;

    // instant-acme 0.8 (audit L-15) : readiness is signalled per-handle via
    // `ChallengeHandle::set_ready()`. Walk the authorizations iterator, find
    // the matching challenge by URL, signal.
    {
        use std::collections::HashSet;
        let target_urls: HashSet<&str> = challenge_urls.iter().map(|s| s.as_str()).collect();
        let mut authorizations = order.authorizations();
        while let Some(result) = authorizations.next().await {
            let mut authz = result.map_err(|e| AcmeError::Order(e.to_string()))?;
            if matches!(authz.status, AuthorizationStatus::Valid) {
                continue;
            }
            let mut challenge = authz
                .challenge(ChallengeType::Dns01)
                .ok_or(AcmeError::NoChallenge("DNS-01"))?;
            if !target_urls.contains(challenge.url.as_str()) {
                continue;
            }
            challenge
                .set_ready()
                .await
                .map_err(|e| AcmeError::Order(e.to_string()))?;
        }
    }

    // Wait for all authorizations to reach Ready (or terminal failure) via
    // the `poll_ready` helper.
    let ready_status = order
        .poll_ready(&RetryPolicy::default())
        .await
        .map_err(|e| AcmeError::Order(e.to_string()))?;
    if ready_status != OrderStatus::Ready {
        return Err(AcmeError::NotReady(format!("{ready_status:?}")));
    }

    finalize_and_poll(&mut order, domains).await
}

/// Generate the CSR, finalize the order, and poll for the issued chain.
/// Shared tail of every issuance path.
async fn finalize_and_poll(
    order: &mut instant_acme::Order,
    domains: &[String],
) -> Result<IssuedCertificate, AcmeError> {
    let (csr_der, key_pem) = generate_csr(domains)?;

    order
        .finalize_csr(&csr_der)
        .await
        .map_err(|e| AcmeError::CertificatePoll(e.to_string()))?;

    // Poll for issuance with exponential backoff. Returns the PEM-encoded
    // certificate chain on success ; the helper handles `Processing` ->
    // `Valid` transitions internally.
    let cert_pem = order
        .poll_certificate(&RetryPolicy::default())
        .await
        .map_err(|e| AcmeError::CertificatePoll(format!("certificate poll failed: {e}")))?;

    Ok(IssuedCertificate { cert_pem, key_pem })
}

#[cfg(test)]
mod tests {
    use super::acme_dns_base_domain;

    #[test]
    fn test_acme_dns_base_domain() {
        assert_eq!(acme_dns_base_domain("example.com"), "example.com");
        assert_eq!(acme_dns_base_domain("*.example.com"), "example.com");
        assert_eq!(acme_dns_base_domain("*.sub.example.com"), "sub.example.com");
        assert_eq!(acme_dns_base_domain("www.example.com"), "www.example.com");
    }
}
