ALTER TABLE routes ADD COLUMN cache_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE routes ADD COLUMN cache_ttl_s INTEGER NOT NULL DEFAULT 300;
ALTER TABLE routes ADD COLUMN cache_max_bytes INTEGER NOT NULL DEFAULT 52428800;
ALTER TABLE routes ADD COLUMN max_connections INTEGER DEFAULT NULL;
ALTER TABLE routes ADD COLUMN slowloris_threshold_ms INTEGER NOT NULL DEFAULT 5000;
ALTER TABLE routes ADD COLUMN auto_ban_threshold INTEGER DEFAULT NULL;
ALTER TABLE routes ADD COLUMN auto_ban_duration_s INTEGER NOT NULL DEFAULT 3600;
